### PR TITLE
ogg-cover-art: Added description as command-line parameter

### PR DESCRIPTION
**Pull request by ivan-tat**

### CODE REVIEW

**Comment by acabal** [comment]
Hi there, if you want to add a description parameter then it should be optional, and we would need it behind a flag so it could accept an empty string. (like `--description=""`).

**Comment by ivan-tat** [comment]
I think the best solution would be:
`ogg-cover-art [-h|--help] [-c FILE|--cover=FILE] [-d TEXT|--description=TEXT] [--] [OUTPUT]`

**Comment by acabal** [comment]
I don't want to change the signature so radically right now; if you want to add description text, then it should just be an optional flag so current users aren't affected.

**Comment by ivan-tat** [comment]
Then this should be fine:
`ogg-cover-art [-h|--help] [-d TEXT|--description=TEXT] [COVER] OUTPUT`

**Comment by acabal** [comment]
OK!

**Pull request closed without merging**
